version: '3.7'
services:
  mariadb:
    image: mariadb:10.8.3-jammy
    container_name: laravelonboarding_app_mariadb
    restart: always
    environment:
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
    ports:
      - '33068:3306'
    networks:
      - laravelonboarding_app_network
    volumes:
      - laravelonboarding_app_mariadb-data:/var/lib/mysql
      - laravelonboarding_app_mariadb-config:/etc/mysql

networks:
  laravelonboarding_app_network:

volumes:
  laravelonboarding_app_mariadb-data:
  laravelonboarding_app_mariadb-config: